image: ros:dashing-ros-base-bionic

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - apt-get update
  - vcs import < instrumentation.repos
  - vcs import < ci_source_deps.repos
  - apt-get install --no-install-recommends -y libasio-dev libtinyxml2-dev
  - rosdep update
  - export RTI_NC_LICENSE_ACCEPTED=yes
  - rosdep install --from-paths . --ignore-src --rosdistro dashing -y --skip-keys "console_bridge fastcdr fastrtps libopensplice67 libopensplice69 rti-connext-dds-5.3.1 urdfdom_headers"

build:
  script:
    - colcon build --symlink-install --packages-up-to tracetools tracetools_test
    - colcon test --packages-select tracetools tracetools_test
  artifacts:
    paths:
      - install
      - build/*/test_results/*/*.xunit.xml
    reports:
      junit: build/*/Testing/*/Test.xml
      
build_enabled:
  script:
    - colcon build --symlink-install --cmake-args " -DWITH_LTTNG=ON" --packages-up-to tracetools tracetools_test
    - colcon test --packages-select tracetools tracetools_test
  artifacts:
    paths:
      - install
      - build/*/test_results/*/*.xunit.xml
    reports:
      junit: build/*/Testing/*/Test.xml
